language: ruby
rvm:
  - 2.0.0
env:
  - DB=sqlite3
  - DB=postgres
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
  - cp config/database.yml.sample config/database.yml
